version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8085:8085 # qBitorrent
      - 8989:8989 # Sonarr
      - 9696:9696 # Prowlarr
      - 7878:7878 # Radarr
      - 34400:34400 # Threadfin
      - 5055:5055 # Jellyseer
      - 8191:8191 # FlareSolverr

    volumes:
      - /home/ubuntu/docker/arr-stack/gluetun:/gluetun
    restart: unless-stopped
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=vpnprovider
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER= 
      - OPENVPN_PASSWORD= 
      # Wireguard:
      # - WIREGUARD_PRIVATE_KEY=<YOUR_PRIVATE_KEY> # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/nordvpn.md#obtain-your-wireguard-private-key
      # - WIREGUARD_ADDRESSES=10.5.0.2/32
      # Timezone for accurate log times
      - TZ=America/Chicago
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=24h
      - FIREWALL_OUTBOUND_SUBNETS=
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - WEBUI_PORT=8085
    volumes:
      - /home/ubuntu/docker/arr-stack/qbittorrent:/config
      - /home/ubuntu/docker/arr-stack/downloads:/downloads
    depends_on:
      - gluetun
    restart: always

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/ubuntu/docker/arr-stack/sonarr/data:/config
      - /home/ubuntu/docker/arr-stack/downloads/tvseries:/tv #optional
      - /home/ubuntu/docker/arr-stack/downloads:/downloads #optional
    restart: always

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/ubuntu//docker/arr-stack/prowlarr/data:/config
    restart: always

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: "service:gluetun"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Chicago
    volumes:
      - /home/ubuntu/docker/arr-stack/flaresolverr/data:/config
    restart: always

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/ubuntu/docker/arr-stack/radarr/data:/config
      - /home/ubuntu/docker/arr-stack/downloads/movies:/tv #optional
      - /home/ubuntu/docker/arr-stack/downloads:/downloads
    restart: always

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    network_mode: "service:gluetun"
    environment:
      - LOG_LEVEL=info
      - TZ=America/Chicago
      - WEBUI_PORT=5055
    volumes:
      - /home/ubuntu/docker/jellyfin/Jellyseerr/config:/app/config
    restart: always

  threadfin:
    image: fyb3roptik/threadfin
    container_name: threadfin
    network_mode: "service:gluetun"
    environment:
      - WEBUI_PORT=34400
      - PUID=1001
      - PGID=1001
      - TZ=America/Chicago
    volumes:
      - /home/ubuntu/docker/arr-stack/threadfin/conf:/home/threadfin/conf
      - /home/ubuntu/docker/arr-stack/threadfin/temp:/tmp/threadfin:rw
    restart: always
