http:
  routers:
    proxmox:
      entryPoints:
        - "https"
      rule: "Host(`proxmox.piercehome.site`)"
      middlewares:
        - default-headers
      tls: {}
      service: proxmox
    unifi:
      entryPoints:
        - https
      rule: "Host(`unifi.piercehome.site`)"
      middlewares:
       - default-headers
      tls: {}
      service: unifi

  services:
    proxmox:
      loadBalancer:
        servers:
          - url: "https://10.0.10.5:8006"
        passHostHeader: true
    unifi:
      loadBalancer:
        servers:
          - url: "https://10.0.0.1"
        passHostHeader: true

  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipWhitelist:
        sourceRange:
        - "10.0.0.0/16"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers